source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('webapp.urls', namespace='webapp')),
    path('auth', include('webauth.urls', namespace="auth"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from webapp.views import CourseDetailView, OrderDetailView, CourseListView, OrderListView, CourseCreateView, CouseUpdateView, \
    CourseDeleteView, OrderCreateView, OrderUpdateView, CourseOrderCreateView, CourseOrderUpdateView, CourseOrderDeleteView, \
    StatusUpdateView, OrderCancelView, CourseOrderAjaxCreateView, CourseOrderAjaxUpdateView, CourseOrderAjaxDeleteView

app_name = 'webapp'

urlpatterns = [
    path('order/<int:pk>', OrderDetailView.as_view(), name='order_detail'),
    path('course/<int:pk>', CourseDetailView.as_view(), name='course_detail'),
    path('', OrderListView.as_view(), name='order_list'),
    path('courses', CourseListView.as_view(), name='course_list'),
    path('courses/create', CourseCreateView.as_view(), name='course_create'),
    path('courses/<int:pk>/update', CouseUpdateView.as_view(), name='course_update'),
    path('courses/<int:pk>/delete', CourseDeleteView.as_view(), name='course_delete'),
    path('orders/create', OrderCreateView.as_view(), name='order_create'),
    path('orders/<int:pk>/update', OrderUpdateView.as_view(), name='order_update'),
    path('order/<int:pk>/courses/add', CourseOrderCreateView.as_view(), name='add_course'),
    path('order/<int:pk>/courses/update', CourseOrderUpdateView.as_view(), name='change_course'),
    path('order/<int:pk>/courses/delete', CourseOrderDeleteView.as_view(), name='delete_course'),
    path('orders/<int:pk>/status_update', StatusUpdateView.as_view(), name='order_status_update'),
    path('orders/<int:pk>/cancel', OrderCancelView.as_view(), name='order_cancel'),
    path('order/<int:pk>/course/create', CourseOrderAjaxCreateView.as_view(), name='order_course_create'),
    path('order/course/<int:pk>/update', CourseOrderAjaxUpdateView.as_view(), name='order_course_update'),
    path('order/course/<int:pk>/delete', CourseOrderAjaxDeleteView.as_view(), name='order_course_delete'),
]

source/webauth/urls.py
from django.urls import path
from webauth.views import login_view, logout_view

app_name = 'auth'

urlpatterns = [
    path('login', login_view, name='login'),
    path('logout', logout_view, name='logout')
]

source/webapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=True,related_name='employee', verbose_name="Сотрудник")
    phone = models.CharField(max_length=50, verbose_name="Телефон")

    def __str__(self):
        return self.user.get_full_name()



class Course(models.Model):
    name = models.CharField(max_length=50, verbose_name="Название блюда")
    price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="Цена")
    photo = models.ImageField(verbose_name='Фотография')

    def __str__(self):
        return self.name


class Order(models.Model):
    STATUS_NEW = 'new'
    STATUS_IN_PROGRESS = 'in progress'
    STATUS_IN_DELIVERY = 'beeing delivered'
    STATUS_DONE = 'done'
    STATUS_CANCELLED = 'cancelled'


    STATUS_CHOICES = (
        (STATUS_NEW, 'новый'),
        (STATUS_IN_PROGRESS, 'в процессе'),
        (STATUS_IN_DELIVERY, 'доставляется'),
        (STATUS_DONE, 'выполненный'),
        (STATUS_CANCELLED, 'отменен')
    )

    client_name = models.CharField(max_length=50, verbose_name="Имя клиента")
    client_phone = models.CharField(max_length=50, verbose_name="Телефон")
    client_address = models.CharField(max_length=50, verbose_name="Адрес")
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, verbose_name="Статус", default=STATUS_NEW)
    operator = models.ForeignKey(User, on_delete=models.PROTECT, related_name='operator_orders', verbose_name='Оператор')
    courier = models.ForeignKey(User, on_delete=models.PROTECT, related_name='courier_orders', verbose_name='Курьер')

    def __str__(self):
        return self.client_phone

    class Meta:
        permissions = [
            ('can_take_and_deliver_orders', "Может брать и доставлять заказы")
        ]

class CourseOrder(models.Model):
    order = models.ForeignKey(Order, related_name='courses', verbose_name='Заказ', on_delete=models.PROTECT)
    course = models.ForeignKey(Course, related_name='ordered', verbose_name='Блюдо', on_delete=models.PROTECT)
    quantity = models.IntegerField(verbose_name='Количество')

    def __str__(self):
        return str(self.course)

source/webapp/forms.py
from django import forms
from webapp.models import Course, Order, CourseOrder

class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        exclude =[]


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ['status', 'operator', 'courier']


class OrderUpdateForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = []


class CourseOrderForm(forms.ModelForm):
    class Meta:
        model = CourseOrder
        exclude = ['order']


class StatusForm(forms.ModelForm):
    class Meta:
        model = Order
        fields=['status']

source/webapp/views.py
from webapp.models import Course, Order, CourseOrder
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView, FormView
from django.urls import reverse, reverse_lazy
from webapp.forms import CourseForm, OrderForm, CourseOrderForm, StatusForm, OrderUpdateForm
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import JsonResponse


class OrderDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView, FormView):
    model = Order
    template_name = 'order_detail.html'
    form_class = CourseOrderForm
    permission_required = 'webapp.view_order'


class OrderListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Order
    template_name = 'order_list.html'
    permission_required = 'webapp.view_order'


class CourseDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Course
    template_name = 'course_detail.html'
    permission_required = 'webapp.view_course'


class CourseListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Course
    template_name = 'course_list.html'
    permission_required = 'webapp.view_course'


class CourseCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Course
    template_name = 'course_create.html'
    form_class = CourseForm
    permission_required = 'webapp.add_course'

    def get_success_url(self):
        return reverse('webapp:course_detail', kwargs={'pk': self.object.pk})


class CouseUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Course
    template_name = 'course_update.html'
    form_class = CourseForm
    success_url = reverse_lazy('webapp:course_list')
    permission_required = 'webapp.change_course'


class CourseDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Course
    template_name = 'course_delete.html'
    success_url = reverse_lazy('webapp:course_list')
    permission_required = 'webapp.delete_course'


class OrderCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Order
    template_name = 'order_create.html'
    form_class = OrderForm
    permission_required = 'webapp.view_order'

    def form_valid(self, form):
        form.instance.status = 'new'
        form.instance.operator = self.request.user
        return super().form_valid(form)


    def get_success_url(self):
        return reverse('webapp:order_detail', kwargs={'pk': self.object.pk})


class OrderUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Order
    template_name = 'order_update.html'
    form_class = OrderUpdateForm
    permission_required = 'webapp.change_order'

    def get_success_url(self):
        return reverse('webapp:order_detail', kwargs={'pk': self.object.pk})


class OrderCancelView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Order
    template_name = 'order_cancel.html'
    form_class = StatusForm
    permission_required = 'webapp.change_order'

    def get(self, request, pk):
        order = get_object_or_404(Order, pk=pk)
        if order.status in ('new', 'preparing'):
            order.status = 'canceled'
        else:
            print("Заказ нельзя отменить")
        order.save()
        return redirect('webapp:order_list')

    def get_success_url(self):
        return reverse('webapp:order_detail', kwargs={'pk': self.object.pk})


class StatusUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Order
    form_class = StatusForm
    permission_required = 'webapp.can_take_and_deliver_orders'

    def get(self, request, pk):
        order = get_object_or_404(Order, pk=pk)
        if order.status == 'in progress':
            order.status = 'beeing delivered'
            order.courier = self.request.user
        elif order.status == 'beeing delivered' and order.courier == self.request.user:
            order.status = 'done'
        order.save()
        return redirect('webapp:order_list')


class CourseOrderCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = CourseOrder
    template_name = 'course_order_create.html'
    form_class = CourseOrderForm
    permission_required = 'webapp.view_courseorder'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['order_pk'] = self.kwargs.get('pk')
        return context

    def form_valid(self, form):
        form.instance.order = Order.objects.get(pk=self.kwargs.get('pk'))
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:order_detail', kwargs={'pk': self.object.order.pk})


class CourseOrderUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = CourseOrder
    template_name = 'course_order_update.html'
    form_class = CourseOrderForm
    permission_required = "webapp.change_courseorder"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['order_pk'] = self.kwargs.get('pk')
        return context

    def form_valid(self, form):
        form.instance.order = Order.objects.get(pk=self.kwargs.get('pk'))
        return super().form_valid(form)


    def get_success_url(self):
        return reverse('webapp:order_detail', kwargs={'pk': self.object.order.pk})


class CourseOrderDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = CourseOrder
    template_name = 'course_order_delete.html'
    permission_required = 'webapp.delete_courseorder'

    def get_success_url(self):
        return reverse('webapp:order_detail', kwargs={'pk': self.object.order.pk})


class CourseOrderAjaxCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = CourseOrder
    form_class = CourseOrderForm
    permission_required = 'webapp.view_courseorder'

    def form_valid(self, form):
        form.instance.order = Order.objects.get(pk=self.kwargs.get('pk'))
        order_course = form.save()
        return JsonResponse({
            'course': order_course.course.name,
            'quantity': order_course.quantity,
            'pk': order_course.pk,
            'course_pk': order_course.course.pk,
            'edit_url': reverse('webapp:order_course_update', kwargs={'pk': order_course.pk})
        })

    def form_invalid(self, form):
        return JsonResponse({
            'errors': form.errors
        }, status='422')


class CourseOrderAjaxUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = CourseOrder
    form_class = CourseOrderForm
    permission_required = "webapp.change_courseorder"

    def form_valid(self, form):
        order_course = form.save()
        return JsonResponse({
            'course': order_course.course.name,
            'quantity': order_course.quantity,
            'pk': order_course.pk,
            'course_pk': order_course.course.pk,

        })

    def form_invalid(self, form):
        return JsonResponse({
            'errors': form.errors
        }, status='422')

class CourseOrderAjaxDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = CourseOrder
    permission_required = 'webapp.delete_courseorder'

    def get_success_url(self):
        return reverse('webapp:order_detail', kwargs={'pk': self.object.order.pk})

source/webapp/templates/course_create.html
{% extends 'base.html' %}

{% block title %}Добавить блюдо{% endblock %}

{% block content %}
    <h1>Добавить блюдо</h1>
    <form action="{% url 'webapp:course_create' %}" method="post" class="form-group" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
{% endblock %}

source/webapp/templates/course_delete.html
{% extends 'base.html' %}
{% block title %}Удалить блюдо{% endblock %}
{% block content %}
    <h1>Удаление проекта</h1>
    <h5>Вы уверены, что хотите удалить блюдо? {{ course.name }}?</h5>
    <form action="{% url 'webapp:course_delete' course.pk %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn, btn-primary">Удалить</button>
    </form>
{% endblock %}

source/webapp/templates/course_list.html
{% extends 'base.html' %}
{% block title %}Заказ{% endblock %}
{% block menu %}
    {% if perms.webapp.add_course %}
    <li class="nav-item">
        <a href="{% url 'webapp:course_create' %}" class="nav-link">Создать блюдо</a>
    </li>
    {% endif %}
{% endblock %}
{% block content %}
    {% for course in course_list %}
        <div class="card" style="width: 18rem;">
          <img src="{{ course.photo.url }}" class="card-img-top" alt="Картинка еды">
          <div class="card-body">
            <h5 class="card-title"><a href="{% url 'webapp:course_detail' course.pk %}" class="nav-link">{{ course.name }}</a></h5>
          </div>
          <ul class="list-group list-group-flush">
                <li class="list-group-item">{{ course.price }}</li>
                {% if perms.webapp.change_course %}
                <li class="list-group-item"><a href="{% url 'webapp:course_update' course.pk %}" class="nav-link">Редактировать</a></li>
                {% endif %}
                {% if perms.webapp.delete_course %}
              <li class="list-group-item"><a href="{% url 'webapp:course_delete' course.pk %}" class="nav-link">Удалить</a></li>
                {% endif %}
          </ul>
        </div>
    {% endfor %}
{% endblock %}

{# Откройте /order/<pk>, чтобы посмотреть список блюд для заказа на этой странице #}

source/webapp/templates/course_order_create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Добавить блюдо в заказ{% endblock %}

{% block content %}
    <form action="{% url 'webapp:add_course' order_pk %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
{% endblock %}

source/webapp/templates/course_order_delete.html
{% extends 'base.html' %}
{% block title %}Удалить блюдо из заказа{% endblock %}
{% block content %}
    <h1>Удаление блюда</h1>
    <h5>Вы уверены, что хотите удалить блюдо из заказа?</h5>
    <form action="{% url 'webapp:delete_course' object.pk %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn, btn-primary">Удалить</button>
    </form>
{% endblock %}

source/webapp/templates/order_cancel.html
{% extends 'base.html' %}

{% block title %}Отменить заказ{% endblock %}

{% block content %}
    <h1>Отменить заказ</h1>
    <h5>Вы уверены, что хотите отменить заказ {{ order.id }}</h5>
    <a href="{% url 'webapp:order_cancel' order.pk %}">Да</a><br>
{% endblock %}

source/webapp/templates/order_detail.html
{% extends 'base.html' %}
{% block title %}Заказ{% endblock %}
{% block content %}
    <h3>Заказ № {{ order.pk }}</h3>
    Клиент: {{ order.client_name }} <br>
    Адресс: {{ order.client_address }} <br>
    Телефон: {{ order.client_phone }} <br>
    <br>
    <h5>Блюда в заказе:</h5>
    <ul id="order_food_list">
        {% for order_course in order.courses.all %}
            <li>
                <span id="order_course_name_{{ order_course.pk }}" data-pk="{{ order_course.course.pk }}">{{ order_course.course.name }}</span>
                <span id="order_course_quantity_{{ order_course.pk }}">{{ order_course.quantity }}</span> шт <br>
                (<a href="{% url 'webapp:order_course_update' order_course.pk %}" data-pk="{{ order_course.pk }}" class="edit_link">Изменить</a>/
                <a href="{% url 'webapp:order_course_delete' order_course.pk %}" class="delete_link">Удалить</a>)
                <hr>
            </li>
        {% endfor %}
    </ul>
    <a href="{% url 'webapp:order_course_create' order.pk %}" id="order_food_add_link">Добавить блюдо + </a> <br>

    <div class="modal" tabindex="-1" role="dialog" id="food_edit_modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Добавить блюда</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form id="course_form" action="{% url 'webapp:order_course_create' order.pk %}" method="post">
                        <div class="text-danger" id="food_form_errors"></div>
                        {% csrf_token %}
                        {{ form.as_p }}
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" id="order_submit">Добавить</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block scripts %}
    <script type="application/javascript">


    function onCreateSuccess(response, status) {
    // выводим содержимое ответа и статус в консоль.

    console.log(response);
    console.log(status);

    // создаём новый пункт списка блюд
    let newFoodLi = $('<li></li>');

    let foodNameSpan = $('<span></span>')
        .attr('id', 'order_course_name_' + response.pk)
        .attr('data-pk', response.course_pk)
        .text(response.course);
    let foodAmountSpan = $('<span></span>')
        .attr('id', 'order_course_quantity_' + response.pk)
        .text(response.quantity);
    let editLink = $('<a></a>')
        .addClass('edit_link')
        .attr('href', response.edit_url)
        .attr('data-pk', response.pk)
        .text('Изменить')
        .click(onOrderCourseUpdate);
    let deleteLink = $('<a></a>')
        .attr('href', '#')
        .text('Удалить');

    newFoodLi
        .attr('id', 'order_course_' + response.pk)
        .append(foodNameSpan)
        .append(document.createTextNode(': '))
        .append(foodAmountSpan)
        .append(document.createTextNode(' шт. ('))
        .append(editLink)
        .append(document.createTextNode(' / '))
        .append(deleteLink)
        .append(document.createTextNode(')'));

    console.log(newFoodLi);
    // добавляем новый пункт в список
    $('#order_food_list').append(newFoodLi);

    // выключаем модальное окно
    $('#food_edit_modal').modal('hide');
}


    // функция, которая обрабатывает успешный AJAX-запрос на изменение блюда
    function onUpdateSuccess(response, status) {
    // выводим содержимое ответа и статус в консоль.
    console.log(response);
    console.log(status);

    // находим нужное блюдо на странице и меняем его данные на новые, пришедшие в ответе
    let pk = response['course_pk'];
    let food_name_span = $('#order_course_name_' + pk);
    food_name_span.text(response.course);
    food_name_span.data('course_pk', response.course_pk);
    $('#order_course_quantity_' + pk).text(response.quantity);
    // прячем модалку
    $('#food_edit_modal').modal('hide');
}


// функция, которая обрабатывает неуспешный AJAX-запрос
// и на добавление, и на изменение блюда
    function onFormSubmitError(response, status) {
    // выводим содержимое ответа и статус в консоль.

    console.log(response);
    console.log(status);

    // если ответ содержит ключ errors,
    // выводим его содержимое в специальный div в модалке
    if (response.errors) {
        $('#food_form_errors').text(response.errors.toString());
    }
}


// функция, которая отправляет AJAX-запрос с формой
// и вызывает переданную функцию в случае успеха
    function orderFoodFormSubmit(success) {
    // определяем url для отправки формы food_form по её свойству action:
    let url = $('#course_form').attr('action');

    // собираем данные, указанные в форме food_form
    let data = {
        course: $('#id_course').val(),
        quantity: $('#id_quantity').val(),
        csrfmiddlewaretoken: $('input[name="csrfmiddlewaretoken"]').val()
    };

    // отправляем данные
    // опции success и error должны быть функциями,
    // которые jQuery вызовет при успешной и неуспешной отправке запроса, соответственно
    // (т.н. "колбэки" - "callback" - функции обратной связи).
    $.ajax({
        url: url,
        method: 'POST',
        data: data,
        success: success,
        error: onFormSubmitError
    });
}


// Обработка клика по ссылке "Добавить"
    function onOrderCourseCreate(event) {
    event.preventDefault();

    // меняем заголовок и текст на кнопке "Добавить" в модалке
    $("#food_edit_modal .modal-title").text('Добавить блюдо');
    $("#order_submit").text('Добавить');

    // меняем action в форме в модалке на url,
    // указанный в href нажатой ссылки на добавление.
    // this в обработчиках событий указывает на тот объект,
    // к которому привязано событие, в данному случае -
    // на ту ссылку, которая была нажата.
    let foodForm = $('#course_form');
    foodForm.attr('action', $(this).attr('href'));

    // сбрасываем данные в форме редактирования блюда в модалке на пустые значения
    $('#id_course').val('');
    $('#id_quantity').val('');

    // отключаем предыдущие обработчики события отправки формы
    foodForm.off('submit');

    // назначаем действие на отправку формы food_form.
    foodForm.on('submit', function (e) {
        // отменить обычную отправку формы (действие по умолчанию с перезагрузкой страницы)
        e.preventDefault();

        // отправить форму с помощью функции orderFoodFormSubmit, которая использует AJAX-запрос.
        // в случае успеха вызвать функцию onCreateSuccess
        orderFoodFormSubmit(onCreateSuccess);
    });

    // показываем модалку на экране
    $('#food_edit_modal').modal('show');
}


    function onOrderCourseUpdate(event) {
        // отменяем действие по умолчанию (переход по ссылке)

        event.preventDefault();

        // меняем заголовок и текст на кнопке "Добавить" в модалке
        $("#food_edit_modal .modal-title").text('Изменить блюдо');
        $("#order_submit").text('Изменить');

        // меняем action в форме в модалке на url,
        // указанный в href нажатой ссылки на редактирование.
        // this в обработчиках событий указывает на тот объект,
        // к которому привязано событие, в данном случае -
        // на ту ссылку, которая была нажата.
        let foodForm = $('#course_form');
        foodForm.attr('action', $(this).attr('href'));

        // находим элементы с именем блюда и количеством блюда на странице,
        // используя свойство data-pk нажатой ссылки.
        let coursePk = $(this).data('pk');
        let courseName = $('#order_course_name_' + coursePk);  // '#order_course_name_1'
        let courseQuantity = $('#order_course_quantity_' + coursePk);  // '#order_course_quantity_1'


        // задаём в форме исходные значения для данного блюда в заказе.
        // т.к. на странице выводится название блюда, а нам нужен его pk,
        // pk сохраняем и получаем через data-атрибут food_pk.
        $('#id_course').val(courseName.data('pk'));
        $('#id_quantity').val(courseQuantity.text());

        // отключаем предыдущие обработчики события отправки формы
        foodForm.off('submit');

        // задаём обработчик события отправки формы
        foodForm.submit(function (event) {
            // отменяем действие по умолчанию (обычная отправка формы)
            event.preventDefault();

            // отправить форму с помощью функции orderFoodFormSubmit, которая использует AJAX-запрос.
            // в случае успеха вызвать функцию onUpdateSuccess
            orderFoodFormSubmit(onUpdateSuccess);
        });

        // показываем модалку на экране.
        $('#food_edit_modal').modal('show');
    }

    function onOrderCourseDelete(event) {
        event.preventDefault();

        if (confirm('Вы действительно хотите удалить блюдо?')) {
            // если пользователь подтверждает удаление, сохраняем ссылку на удаляемое блюдо
            // из атрибута 'href' в переменную url
            let url = $(this).attr('href');

            // находим родительский элемент (само блюдо) и сохраняем его в переменную item
            let item = $(this).parent('li');

            // делаем AJAX-запрос на удаление блюда
            $.ajax({
                url: url,
                method: 'POST',
                data: {
                    csrfmiddlewaretoken: $('input[name="csrfmiddlewaretoken"]').val()
                },
                success: function (response, status) {
                    // если от сервера пришло подтверждение удаления, удаляем html-элемент на странице
                    item.remove();
                }
            })
        }
    }


window.addEventListener('load', function () {
    // назначаем действие на нажатие кнопки "Добавить" в модалке.
    // кнопка не находится внутри формы, поэтому её требуется настроить здесь.
    $('#order_submit').on('click', function (e) {
        // отправляем форму
        $('#course_form').submit();
    });

    // настраиваем создание блюд по клику на ссылку "Добавить"
    $("#order_food_add_link").click(onOrderCourseCreate);

    // настраиваем изменение блюд по клику на ссылки "Изменить"
    $('#order_food_list .edit_link').click(onOrderCourseUpdate);

    //$('#order_food_list').on('click', '.edit_link', onOrderCourseUpdate);

    // настраиваем изменение блюд по клику на ссылки "Удалить"
    $('#order_food_list .delete_link').click(onOrderCourseDelete);
});

    </script>

{% endblock %}
{# Откройте /order/<pk>, чтобы посмотреть список блюд для заказа на этой странице #}

source/webapp/templates/order_list.html
{% extends 'base.html' %}
{% block title %}Заказ{% endblock %}
{% block menu %}
    {% if perms.webapp.add_order %}
    <li class="nav-item">
        <a href="{% url 'webapp:order_create' %}" class="nav-link">Создать заказ</a>
    </li>
    {% endif %}
{% endblock %}
{% block content %}
    {% for order in order_list %}
        Имя: {{ order.client_name }} <br>
        Адресс: {{ order.client_address }} <br>
        Телефон: {{ order.client_phone }} <br>
        Статус: {{ order.get_status_display }} <br>
        Курьер: {{ order.courier }} <br>
        Оператор: {{ order.operator }} <br>
        {% if perms.webapp.view_order %}
        <a href="{% url 'webapp:order_detail' order.pk %}">Подробнее</a> <br>
        {% endif %}
        {% if perms.webapp.change_order %}
        <a href="{% url 'webapp:order_update' order.pk %}">Редактировать</a> <br>
        {% endif %}
        {% if perms.webapp.change_courseorder %}
        <a href="{% url 'webapp:add_course' order.pk %}">Добавить блюдо</i></a> <br>
        {% endif %}
        {% if perms.webapp.can_take_and_deliver_orders %}
            {% if order.status == 'in progress' %}
                <a href="{% url 'webapp:order_status_update' order.pk %}">Взять заказ</a><br>
            {% elif order.status == 'beeing delivered' %}
                <a href="{% url 'webapp:order_status_update' order.pk %}">Отметить как доставленный</a><br>
            {% endif %}
        {% endif %}
         <hr>
    {% endfor %}
{% endblock %}